### PR TITLE
Update docs styling

### PR DESCRIPTION
**Pull request by coffee-cup**
- Update sidebar search
- Update sidebar headings
- Update code theme

Before

image

After

image

### CODE REVIEW

**Comment by andrejak** [comment]
I like the sidebar, although maybe the left padding for the subsections could be even a bit bigger to help distinguish them when you have multiple sections expanded?

This may be just a personal preference, but I'm not a fan of using purple for links as I associate with already clicked ones. I also have mixed feelings about purple (links, code bg) and green (logo, sidebar, buttons...) as a [colour combination](https://comicvine.gamespot.com/profile/captaincockblock/lists/green-and-purple-the-colors-of-evil/35647/).

Feel free to ignore if you disagree :)

**Comment by coffee-cup** [comment]
I personally like green and purple as a combination haha. The link colour is completely arbitrary though. We could use the same colour as the selected sidebar colour? Any preference @sunirmehta 

image

**Comment by coffee-cup** [comment]
Going to merge as is so that the docs look better for any beta testers that visit it this weekend. We can discuss colour changes on Monday.

**Comment by sunirmehta** [comment]
Green and purple combination looks neat. 
Thinking of the URL colour right now as green denotes the _active link_ (in sidebar). Perhaps a shade of blue works, will try out a few more combos.

**Pull request merged**
