### PR TITLE
Plugin creation change

### PR DESCRIPTION
**Pull request by coffee-cup**
New way to create plugins that hopefully has better typing and action creation. 

Main changes include

- plugins are parametrized by an optional event type now
- plugin name tracked with events (defaults to `(name)` for user actions)
- plugins are created with `createPlugin` (see concerns with this below)

Instead of creating the `ProdoPlugin` object manually, you create the plugin by calling `createPlugin`. The signature is,

```ts
export const createPlugin = <
  InitOptions,
  Universe,
  ActionCtx,
  ViewCtx,
  CustomEvent = {}
>(
  name: string,
): ProdoPlugin<InitOptions, Universe, ActionCtx, ViewCtx, CustomEvent> => { 
  /* ... */ 
}
```

## Plugin Functions

You can add plugin functions such as `init` or `prepareActionCtx` by calling the appropriate functions on the `plugin`. When they are defined inline, the types are inferred,

```ts
effect.prepareActionCtx(({ ctx, event }, config) => {
  /* ... */
});
```

Or you can define them separatly and import the type,

```ts
const prepareActionCtx = <T>(): PluginActionCtxFn<
  Config<T>,
  Universe<T>,
  ActionCtx<T>
> => ({ ctx, universe }, config) => {
  /* ... */
}

// later on...

plugin.prepareActionCtx(prepareActionCtx<T>());
```

## Plugin Actions

You can define plugin actions in a similar way to how you define model actions, using `plugin.action`. All of the types should be inferred. Plugin actions require a name.

```ts
const updateRandomAction = plugin.action(
  ({ random }) => (key: string, possibilities: unknown[]) => {
    random[key] = randomValue(possibilities);
  },
  "updateRandom",
);
```

## Concerns

One thing I am a little unsure about is how nested things can get. If the plugin requires a type parameter, such as the DB, then the plugin must be created in a function, meaning plugin actions must be created in the function and anything that uses the plugin action must also be created in the action. For example,

```ts
const firestorePlugin = <DB>(): ProdoPlugin<
  Config<DB>,
  Universe,
  ActionCtx<DB>,
  ViewCtx<DB>
> => {
  const plugin = createPlugin<Config<DB>, Universe, ActionCtx<DB>, ViewCtx<DB>>(
    "firestore",
  );

  const pluginAction = plugin.action(/* ... */);

  /* ... */

  return plugin;
};
```

This essentially means that everything for these types of plugins must be defined 1 level deep. I will think about/explore ways to prevent this. However, I do like that with this system

- plugin actions must have a name
- plugin actions will automatically know which plugin they originated from
- types are inferred

Some possible solutions to the above problem are

- Expose a `createPluginAction` function that takes the action name, plugin name, and action function. But to call it with a type parameter you will have to have `dispatch(myPluginAction())(...args)`
- Have separate `createPluginModel` and `pluginModel.create` methods. But still not sure if that would fix the type param problem

### CODE REVIEW

**Comment by tdawes** [comment]
Plugins that are created via a function will cause a problem, because we need to be able to export the actions.

**Comment by coffee-cup** [comment]
@tdawes I'm not sure we should be monkey patching the type like that. What do you think about having the `createPluginAction` method? It would probably look something like

```ts
// @prodo/firestore
import { createPluginAction } from "@prodo/core";

export const myAction = createPluginAction<ActionCtx<any>>("myAction", "firestore", 
  ctx => params => {}
);
```

but then that introduces an `any`

**Comment by coffee-cup** [comment]
I believe after a discussion we decided that plugins that export type action can just add the actions to the action or view contexts. This PR is ready for review

**Comment by Onurbon** [comment]
I haven't had time to dig into the details but it all looks and sound quite sensible to me. The one thing I didn't follow is why bothering with inferred types 
```
const createPlugin = <
  InitOptions,
  Universe,
  ActionCtx,
  ViewCtx,
  CustomEvent = {}
>(
  name: string,
): ProdoPlugin<InitOptions, Universe, ActionCtx, ViewCtx, CustomEvent> => {
    ...
  };
```
instead of specifying types like this 
```
function createPlugin<
  InitOptions,
  Universe,
  ActionCtx,
  ViewCtx,
  CustomEvent = {}
>(
  name: string,
): ProdoPlugin<InitOptions, Universe, ActionCtx, ViewCtx, CustomEvent> {
    ...
  };
```
I'm thinking the latter would address the concern you raised in the summary and wouldn't make life that much harder for plugin authors.

**Comment by coffee-cup** [comment]
@tdawes please see latest changes regarding routing plugin and let me know what you think.

**Pull request merged**
